apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secrets-store-csi-driver-provider-infisical.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets-store-csi-driver-provider-infisical.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
