apiVersion: v1
kind: Service
metadata:
  name: {{ include "secrets-store-csi-driver-provider-infisical.fullname" . }}
  labels:
    {{- include "secrets-store-csi-driver-provider-infisical.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "secrets-store-csi-driver-provider-infisical.selectorLabels" . | nindent 4 }}
