{{- if .Values.webhook.enable }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "secrets-store-csi-driver-provider-infisical.webhook.fullname" . }}
  labels:
    {{- include "secrets-store-csi-driver-provider-infisical.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.caInjection }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "secrets-store-csi-driver-provider-infisical.webhook.fullname" . }}
  {{- end }}
webhooks:
- name: msecretproviderclass.kb.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "secrets-store-csi-driver-provider-infisical.webhook.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /webhooks/mutating/secretproviderclass
  failurePolicy: Fail
  rules:
  - apiGroups:
    - secrets-store.csi.x-k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secretproviderclasses
  sideEffects: None
{{- end }}
