apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-csi-provider
  namespace: default
  labels:
    app: test-csi-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-csi-provider
  template:
    metadata:
      labels:
        app: test-csi-provider
    spec:
      containers:
      - name: client
        image: busybox:latest
        command: ["sh", "-c"]
        args:
        - |
          set -eux
          ls /run/secrets
          find /run/secrets/ -mindepth 1 -maxdepth 1 -not -name '.*' | xargs -t -I {} sh -c 'echo "$(cat "{}")"'
          tail -f /dev/null
        volumeMounts:
        - name: data
          mountPath: /run/secrets
      volumes:
      - name: data
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "test-csi-provider"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-csi-provider
  namespace: default
spec:
  provider: infisical
  parameters:
    projectSlug: example-project-em-9-e
    envSlug: dev
    secretsPath: / # optional,default="/"
    authSecretName: infisical-secret-provider-auth-credentials
    authSecretNamespace: default
    objects: |
      - objectName: DATABASE_URL
      - objectName: DB_USERNAME
      - objectName: DB_PASSWORD
  secretObjects:
  - secretName: test-csi-provider
    type: Opaque
    data:
    - objectName: DATABASE_URL
      key: url
