---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-csi-driver-provider-infisical
  namespace: kube-system
  labels:
    app.kubernetes.io/name: secrets-store-csi-driver-provider-infisical
    app.kubernetes.io/instance: secrets-store-csi-driver-provider-infisical
    app.kubernetes.io/version: "1.0.1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-store-csi-driver-provider-infisical
  namespace: kube-system
  labels:
    app.kubernetes.io/name: secrets-store-csi-driver-provider-infisical
    app.kubernetes.io/instance: secrets-store-csi-driver-provider-infisical
    app.kubernetes.io/version: "1.0.1"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-store-csi-driver-provider-infisical
  namespace: kube-system
  labels:
    app.kubernetes.io/name: secrets-store-csi-driver-provider-infisical
    app.kubernetes.io/instance: secrets-store-csi-driver-provider-infisical
    app.kubernetes.io/version: "1.0.1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-store-csi-driver-provider-infisical
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: secrets-store-csi-driver-provider-infisical
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: secrets-store-csi-driver-provider-infisical
  namespace: kube-system
  labels:
    app.kubernetes.io/name: secrets-store-csi-driver-provider-infisical
    app.kubernetes.io/instance: secrets-store-csi-driver-provider-infisical
    app.kubernetes.io/version: "1.0.1"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: secrets-store-csi-driver-provider-infisical
      app.kubernetes.io/instance: secrets-store-csi-driver-provider-infisical
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secrets-store-csi-driver-provider-infisical
        app.kubernetes.io/instance: secrets-store-csi-driver-provider-infisical
        app.kubernetes.io/version: "1.0.1"
    spec:
      serviceAccountName: secrets-store-csi-driver-provider-infisical
      securityContext:
        {}
      containers:
        - name: secrets-store-csi-driver-provider-infisical
          image: "gidoichi/secrets-store-csi-driver-provider-infisical:v1.0.1"
          imagePullPolicy: IfNotPresent
          resources:
            {}
          volumeMounts:
            - name: socket
              mountPath: /etc/kubernetes/secrets-store-csi-providers
      volumes:
        - name: socket
          hostPath:
            path: /etc/kubernetes/secrets-store-csi-providers
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/os: linux
