apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: example-provider-infisical
  namespace: default
spec:
  provider: infisical
  parameters:
    projectSlug: TODO: REPLACEME
    envSlug: dev
    secretsPath: / # optional,default="/"
    authSecretName: infisical-secret-provider-auth-credentials
    authSecretNamespace: default
    objects: |
      - objectName: DATABASE_URL
      - objectName: DB_USERNAME
      - objectName: DB_PASSWORD
  secretObjects:
  - secretName: example-provider-infisical
    type: Opaque
    data:
    - objectName: DATABASE_URL
      key: url
