name: Publish
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
jobs:
  container-image:
    runs-on: ubuntu-latest
    environment:
      name: dockerhub
      url: https://hub.docker.com/r/${{ github.repository }}
    steps:
      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          username: gidoichi
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        id: docker
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:${{ inputs.tag }},${{ github.repository }}:latest
      - id: sha256
        env:
          digest: ${{ steps.docker.outputs.digest }}
        run: echo "digest=${digest#sha256:}" >> "$GITHUB_OUTPUT"

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4
      - name: Generate Charts
        working-directory: charts
        run: |
          set -eux
          helm package secrets-store-csi-driver-provider-infisical
          for file in *.tgz; do mv {,chart-}"$file"; done
      - uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2
        with:
          files: charts/chart-*.tgz
          tag_name: ${{ inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
