name: Publish container image on Pull Request
on:
  workflow_call:
    outputs:
      digest:
        value: ${{ jobs.publish.outputs.digest }}
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.docker.outputs.digest }}
    steps:
      - uses: docker/login-action@v3
        with:
          username: gidoichi
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        id: docker
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:latest
