name: Publish container image on Pull Request
on:
  workflow_call:
    outputs:
      digest:
        value: ${{ jobs.publish.outputs.digest }}
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.docker.outputs.digest }}
    steps:
      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          username: gidoichi
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        id: docker
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:latest
