name: Release
on:
  push:
    branches: ["main"]
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      old-tag: ${{ steps.old-tag.outputs.tag }}
      new-tag: v${{ steps.version.outputs.runtime }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: old-tag
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Get runtime version
        id: version
        run: printf 'runtime=%s' "$(go run main.go --version)" >> "$GITHUB_OUTPUT"

  tag:
    needs: check
    if: ${{ needs.check.outputs.new-tag != needs.check.outputs.old-tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: ${{ needs.check.outputs.new-tag }}

  container:
    needs: check
    if: ${{ needs.check.outputs.new-tag != needs.check.outputs.old-tag }}
    permissions:
      contents: write
    uses: ./.github/workflows/publish-container.yml
    secrets: inherit
    with:
      tag: ${{ needs.check.outputs.new-tag }}

  gh-release:
    needs: [check, tag]
    if: ${{ needs.check.outputs.new-tag != needs.check.outputs.old-tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: azure/setup-helm@v5
      - name: Generate Charts
        working-directory: charts
        run: |
          set -eux
          helm package secrets-store-csi-driver-provider-infisical
          for file in *.tgz; do mv {,chart-}"$file"; done
      - uses: softprops/action-gh-release@v3
        with:
          files: charts/chart-*.tgz
          tag_name: ${{ needs.check.outputs.new-tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
