name: Test
on:
  workflow_dispatch:
  push:
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
        with:
          push: false

  go-test:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.runtime }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Version
        id: version
        run: |
          set -x
          printf 'runtime=%s' "$(go run main.go --version)" >> "$GITHUB_OUTPUT"

  helm-chart:
    runs-on: ubuntu-latest
    needs: go-test
    steps:
      - uses: actions/checkout@v4
      - name: Match provider version
        uses: mikefarah/yq@v4.44.3
        env:
          PROVIDER_VERSION: ${{ needs.go-test.outputs.version }}
        with:
          cmd: |
            file="charts/secrets-store-csi-driver-provider-infisical/Chart.yaml"
            diff <(yq --prettyPrint '.appVersion = strenv(PROVIDER_VERSION)' "$file") <(yq --prettyPrint "$file") >&2
