on:
  workflow_dispatch:
  push:
jobs:
  e2e-test:
    if: "false"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: mig4/setup-bats@v1
        with:
          bats-version: 1.11.0
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.24.0
          image: "kindest/node:v1.30.4"
      - name: Test
        run: |
          helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
          helm install secrets-store-csi-driver secrets-store-csi-driver/secrets-store-csi-driver --version v1.4.5 --set syncSecret.enabled=true
          make IMAGE_TAG=pull${{ github.event.number }} e2e-windows
