on:
  workflow_call:
    inputs:
      image-tag:
        required: false
        type: string
      tag-type:
        required: false
        type: string
      type:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      type:
        required: false
        type: string
jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.determined.outputs.tag }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Get the latest tag
        id: latest
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true
      - name: Determine tag
        id: determined
        env:
          TAG_TYPE: ${{ inputs.tag-type }}
          INPUT_TAG: ${{ inputs.image-tag }}
          LATEST_TAG: ${{ steps.latest.outputs.old_tag }}
        run: |
          set -eux
          case "$TAG_TYPE" in
              input|'')   echo "tag=$INPUT_TAG"  >> "$GITHUB_OUTPUT" ;;
              latest-tag) echo "tag=$LATEST_TAG" >> "$GITHUB_OUTPUT" ;;
              latest)     echo "tag=latest"      >> "$GITHUB_OUTPUT" ;;
          esac

  e2e-test:
    needs: tag
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true
      - uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1
        with:
          # renovate: datasource=github-tags depName=bats-core/bats-core versioning=semver
          bats-version: 1.12.0
      - uses: engineerd/setup-kind@aa272fe2a7309878ffc2a81c56cfe3ef108ae7d0 # v0.5.0
        with:
          # renovate: datasource=github-tags depName=kubernetes-sigs/kind versioning=semver
          version: v0.29.0
          image: kindest/node:v1.33.2
      - name: Test
        env:
          CLIENT_ID: ${{ secrets.E2E_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.E2E_CLIENT_SECRET }}
          IMAGE_TAG: ${{ needs.tag.outputs.value }}
          PROJECT_SLUG: ${{ secrets.E2E_PROJECT_SLUG }}
          SECRET_NAME: ${{ secrets.E2E_SECRET_NAME }}
          SECRET_VALUE: ${{ secrets.E2E_SECRET_VALUE }}
          TYPE: ${{ inputs.type }}
        run: |
          helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
          helm install secrets-store-csi-driver secrets-store-csi-driver/secrets-store-csi-driver --version 1.5.3 --set syncSecret.enabled=true
          if [ -z "$TYPE" ]; then
            make e2e
          else
            make "e2e-$TYPE"
          fi
